---
- hosts: router
  roles:
    - router
  tags:
    - router

- hosts: dc
  roles:
    - dc
    - windows
  tags:
    - dc

- hosts: wef
  roles:
    - wef
    - windows
  tags:
    - wef

- hosts: windows_workstations
  roles:
    - windows_workstation
    - windows
  tags:
    - windows_workstations

- hosts: dc
  roles:
    - final_touches
  tags:
    - final_touches

- hosts:
  - dc
  - wef
  - windows_workstations
  roles:
    - reboot
  tags:
    - reboot